apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: mynamespace
spec:
  type: LoadBalancer 
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432